server:
  port: 1000
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        #database-platform: org.hibernate.dialect.MySQL5Dialect