server:
 port: 9999
 
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
     hibernate:
      format-sql: true
      #dialect: org.hibernate.dialect.MySQLDialect
    
      